"""PlatformIO extra_script: inject WEB_MODULE_VERSION from library.json.

This script generates include/version_autogen.h at build time, extracting
the version string from library.json and defining WEB_MODULE_VERSION_STR.

Usage:
    Add to platformio.ini: extra_scripts = pre:scripts/inject_version_define.py
    Add to .gitignore: include/version_autogen.h

The generated header will cause a compile error if library.json is missing
or does not contain a "version" field (intentional safety mechanism).
"""

import json
import os

from SCons.Script import Import

Import("env")

# Determine module name from library.json for logging
project_dir = env["PROJECT_DIR"]
lib_json_path = os.path.join(project_dir, "library.json")

module_name = "unknown"
version = None

try:
    with open(lib_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        module_name = data.get("name", "unknown")
        version = data.get("version")
except FileNotFoundError:
    print(f"[version_inject] ERROR: library.json not found at {lib_json_path}")
except Exception as e:
    print(f"[version_inject] ERROR: Failed to read library.json: {e}")

# Generate version header
header_dir = os.path.join(project_dir, "include")
os.makedirs(header_dir, exist_ok=True)
header_path = os.path.join(header_dir, "version_autogen.h")

if version:
    with open(header_path, "w", encoding="utf-8") as hf:
        hf.write("// Auto-generated by inject_version_define.py - DO NOT EDIT\n")
        hf.write("// Source: library.json\n\n")
        hf.write("#ifndef VERSION_AUTOGEN_H\n")
        hf.write("#define VERSION_AUTOGEN_H\n\n")
        hf.write(f'#define WEB_MODULE_VERSION_STR "{version}"\n')
        hf.write(f'#define WEB_MODULE_VERSION "{version}"\n\n')
        hf.write("#endif // VERSION_AUTOGEN_H\n")
    print(f"[{module_name}] Generated version_autogen.h: v{version}")
else:
    # Write a header that triggers compile error
    with open(header_path, "w", encoding="utf-8") as hf:
        hf.write("// Auto-generated by inject_version_define.py\n")
        hf.write(
            '#error "Version missing from library.json - add \\"version\\" field"\n'
        )
    print(f"[{module_name}] ERROR: No version in library.json (build will fail)")
