// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef WEB_MODULE_EXAMPLE_VERSION_AUTOGEN_H
#define WEB_MODULE_EXAMPLE_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.1.1"
#define WEB_MODULE_VERSION "0.1.1"

#endif // WEB_MODULE_EXAMPLE_VERSION_AUTOGEN_H
